---

    - name: Обновить пакеты
      yum:
        name: '*'
        state: latest
      vars:
        update_cache: yes

    - name: Установить epel-release и yum-utils
      yum:
        name: 
          - epel-release
          - yum-utils
        state: present

    - name: Установить remi-release
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

    - name: Обновить пакеты из remi репозитория
      yum:
        name: '*'
        enablerepo: remi,remi-php81
        state: latest

    - name: Удалить PHP и php-fpm
      yum:
        name: php,php-fpm
        state: absent

    - name: Удалить все пакеты PHP
      yum:
        name: php*
        state: absent

    - name: Отключить старые версии репозитория remi-php
      command: yum-config-manager --disable 'remi-php*'

    - name: Включить репозиторий remi-php81
      command: yum-config-manager --enable remi-php81

    - name: Установить необходимые пакеты PHP
      yum:
        name:
          - php
          - php-cli
          - php-fpm
          - php-mysqlnd
          - php-zip
          - php-devel
          - php-gd
          - php-mbstring
          - php-curl
          - php-xml
          - php-pear
          - php-bcmath
          - php-json
          - php-opcache
          - php-redis
          - php-memcache
        state: present

    - name: Uncomment and set listen.owner, listen.group, user, and group in www.conf
      replace:
        path: /etc/php-fpm.d/www.conf
        regexp: '{{ item.regexp }}'
        replace: '{{ item.replace }}'
        backup: yes
      loop:
        - { regexp: '^;?listen.owner =.*', replace: 'listen.owner = nginx' }
        - { regexp: '^;?listen.group =.*', replace: 'listen.group = nginx' }
        - { regexp: '^;?user =.*', replace: 'user = nginx' }
        - { regexp: '^;?group =.*', replace: 'group = nginx' }
    
    - name: Update listen parameter in www.conf
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen = .*'
        line: 'listen = /var/run/php-fpm/php-fpm.sock'
        state: present

    - name: Add cgi.fix_pathinfo=0 to php.ini
      lineinfile:
        path: /etc/php.ini
        line: 'cgi.fix_pathinfo=0'
        insertafter: EOF

    - name: Start and enable php-fpm
      systemd:
        name: php-fpm
        enabled: yes
        state: restarted